GO
USE MAGAZIN_DE_JOCURI
GO



--- TRANZACTIA 2 ---


----------------- DIRTY READS -----------------

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED		-- dirty reads
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED		-- solutie dirty reads
BEGIN TRAN
SELECT * FROM JOCURI
WAITFOR DELAY '00:00:05'
SELECT * FROM JOCURI
COMMIT TRAN


------------- NON-REPEATABLE READS ------------

SET TRANSACTION ISOLATION LEVEL READ COMMITTED			-- non-repetable reads
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ		-- solutie non-repetable reads
BEGIN TRAN
SELECT * FROM JOCURI
WAITFOR DELAY '00:00:05'
SELECT * FROM JOCURI
COMMIT TRAN


---------------- PHANTOM READS ----------------

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ			-- phantom reads
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE			-- solution phantom reads
BEGIN TRAN
SELECT * FROM JOCURI
WAITFOR DELAY '00:00:05'
SELECT * FROM JOCURI
COMMIT TRAN


------------------ DEADLOCK -------------------

GO
CREATE OR ALTER PROCEDURE deadlock_tran2
AS
BEGIN
	BEGIN TRAN
	-- blocare tabela JOCURI
	UPDATE JOCURI SET nume = 'Deadlock TRAN 2' where Jid = 1095
	WAITFOR DELAY '00:00:05'
	-- incercare blocare tabelei PLATFORME
	UPDATE PLATFORME SET nume = 'Deadlock TRAN 2' where Pid = 21
	COMMIT TRAN
END
GO

EXEC deadlock_tran2
SELECT * FROM JOCURI
SELECT * FROM PLATFORME